apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-config
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app: hello-kubernetes-config
