apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-kubernetes-config
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hello-kubernetes-config
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hello-kubernetes-config
  namespace: default
subjects:
  - kind: ServiceAccount
    name: hello-kubernetes-config
    namespace: default
roleRef:
  kind: ClusterRole
  name: view